//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПОКУПАТЕЛЬ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПОКУПАТЕЛЬ()
        {
            this.ПРОДАЖА = new HashSet<ПРОДАЖА>();
        }
    
        public int ИдентификаторПокупателя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Телефон { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПРОДАЖА> ПРОДАЖА { get; set; }
    }
}
