//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПРОДУКТ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПРОДУКТ()
        {
            this.ЭЛЕМЕНТ_ПРОДАЖИ = new HashSet<ЭЛЕМЕНТ_ПРОДАЖИ>();
        }
    
        public int ИдентификаторПродукта { get; set; }
        public string НазваниеПродукта { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> ИдентификаторМагазина { get; set; }
    
        public virtual МАГАЗИН МАГАЗИН { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭЛЕМЕНТ_ПРОДАЖИ> ЭЛЕМЕНТ_ПРОДАЖИ { get; set; }
    }
}
