//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПРОДАЖА
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПРОДАЖА()
        {
            this.ЭЛЕМЕНТ_ПРОДАЖИ = new HashSet<ЭЛЕМЕНТ_ПРОДАЖИ>();
        }
    
        public int ИдентификаторПродажи { get; set; }
        public Nullable<int> ИдентификаторПокупателя { get; set; }
        public Nullable<System.DateTime> ДатаПродажи { get; set; }
        public Nullable<decimal> ОбщаяСумма { get; set; }
    
        public virtual ПОКУПАТЕЛЬ ПОКУПАТЕЛЬ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЭЛЕМЕНТ_ПРОДАЖИ> ЭЛЕМЕНТ_ПРОДАЖИ { get; set; }
    }
}
