//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class СОТРУДНИК
    {
        public int ИдентификаторСотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> ИдентификаторМагазина { get; set; }
        public string Должность { get; set; }
    
        public virtual МАГАЗИН МАГАЗИН { get; set; }
    }
}
